#!/usr/bin/env python3
"""
Initialize the database on a new system: create DB/user, run migrations, verify.

Run from project root. Ensures .env exists, optionally creates PostgreSQL
database and user, runs Alembic migrations, and verifies connection and tables.

Usage:
  python scripts/initialize_database.py
      Ensure .env exists, run migrations, verify (DB/user must already exist).

  python scripts/initialize_database.py --create-db
      Create PostgreSQL user and database, write DATABASE_URL to .env,
      then run migrations and verify. Requires sudo for psql as postgres.

  python scripts/initialize_database.py --create-db --db-name samgov_db --db-user samgov_user
      Custom database name and user (defaults: samgov_db, samgov_user).

  python scripts/initialize_database.py --sync-password
      Set PostgreSQL user password to match DATABASE_URL in .env (requires sudo).

Requirements:
  - PostgreSQL installed and running (for --create-db: postgres user must exist).
  - DATABASE_URL in .env (or created by --create-db).
  - Python deps: run from project with backend on path (e.g. venv with app deps).
"""
import argparse
import os
import re
import subprocess
import sys

# Project root (parent of scripts/)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)


def _ensure_project_root():
    os.chdir(PROJECT_ROOT)
    if not os.path.isdir("backend") or not os.path.isfile("alembic.ini"):
        print("Error: Run from project root (directory containing backend/ and alembic.ini).")
        sys.exit(1)


def _ensure_backend_path():
    backend_dir = os.path.join(PROJECT_ROOT, "backend")
    if backend_dir not in sys.path:
        sys.path.insert(0, PROJECT_ROOT)
        sys.path.insert(0, backend_dir)


def _env_path():
    return os.path.join(PROJECT_ROOT, ".env")


def _ensure_env():
    """Create minimal .env if missing; do not overwrite."""
    env_file = _env_path()
    if os.path.isfile(env_file):
        return
    example = os.path.join(PROJECT_ROOT, ".env.example")
    if os.path.isfile(example):
        with open(example, "r") as f:
            content = f.read()
        with open(env_file, "w") as f:
            f.write(content)
        print("Created .env from .env.example")
        return
    # Minimal .env
    default_url = "postgresql://postgres:postgres@localhost:5432/samgov_db"
    lines = [
        "# Generated by scripts/initialize_database.py",
        "DATABASE_URL=" + default_url,
        "SECRET_KEY=",
        "JWT_SECRET_KEY=",
        "REDIS_URL=redis://localhost:6379/0",
        "REDIS_CELERY_URL=redis://localhost:6379/1",
    ]
    with open(env_file, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("Created minimal .env with default DATABASE_URL. Edit .env and re-run if needed.")


def _load_database_url():
    _ensure_backend_path()
    from backend.app.core.config import settings
    return settings.DATABASE_URL


def _parse_db_url(url: str):
    """Return (user, password, host, port, dbname) from postgresql://user:pass@host:port/dbname."""
    m = re.match(
        r"postgresql(?:\+[a-z0-9]+)?://([^:]+):([^@]*)@([^:/]+):?(\d+)?/(.+)",
        url.strip(),
    )
    if not m:
        return None
    user, password, host, port, dbname = m.groups()
    port = port or "5432"
    return user, password, host, port, dbname


def _run_psql(sql: str, as_user: str = "postgres", database: str = "postgres"):
    """Run SQL via psql as system user. Returns (success, stderr)."""
    cmd = ["sudo", "-u", as_user, "psql", "-d", database, "-v", "ON_ERROR_STOP=1", "-t", "-A", "-c", sql]
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=PROJECT_ROOT)
    return r.returncode == 0, (r.stderr or r.stdout or "").strip()


def _create_db_and_user(db_name: str, db_user: str, db_password: str) -> bool:
    """Create PostgreSQL user and database. Returns True on success."""
    ok, out = _run_psql(
        f"SELECT 1 FROM pg_roles WHERE rolname = '{db_user}'",
        database="postgres",
    )
    if not ok:
        print("Could not check existing users:", out)
        return False
    user_exists = out.strip() == "1"

    if not user_exists:
        # CREATE USER with password (escape single quotes in password)
        pwd_esc = db_password.replace("'", "''")
        ok, err = _run_psql(f"CREATE USER \"{db_user}\" WITH PASSWORD '{pwd_esc}';", database="postgres")
        if not ok:
            print("Failed to create user:", err)
            return False
        print("Created PostgreSQL user:", db_user)

    # Create database (idempotent: ignore if exists)
    ok2, out2 = _run_psql(
        f"SELECT 1 FROM pg_database WHERE datname = '{db_name}'",
        database="postgres",
    )
    db_exists = ok2 and (out2 or "").strip() == "1"
    if not db_exists:
        ok, err = _run_psql(
            f'CREATE DATABASE "{db_name}" OWNER "{db_user}";',
            database="postgres",
        )
        if not ok:
            print("Failed to create database:", err)
            return False
        print("Created database:", db_name)

    ok, err = _run_psql(
        f'GRANT ALL PRIVILEGES ON DATABASE "{db_name}" TO "{db_user}";',
        database="postgres",
    )
    if not ok:
        print("Grant database warning:", err)
    ok, err = _run_psql(
        f'GRANT ALL ON SCHEMA public TO "{db_user}";',
        database=db_name,
    )
    if not ok:
        print("Grant schema warning:", err)
    return True


def _sync_password(db_user: str, password: str) -> bool:
    pwd_esc = password.replace("'", "''")
    ok, err = _run_psql(f"ALTER USER \"{db_user}\" WITH PASSWORD '{pwd_esc}';", database="postgres")
    if not ok:
        print("Failed to set password:", err)
        return False
    print("Updated password for user:", db_user)
    return True


def _run_migrations() -> bool:
    r = subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        print("Migrations failed:")
        print(r.stdout or "")
        print(r.stderr or "")
        return False
    print("Migrations: OK")
    return True


def _verify_connection():
    """Connect and list tables. Returns True if OK."""
    _ensure_backend_path()
    from sqlalchemy import text
    from backend.app.core.database import engine
    try:
        with engine.connect() as conn:
            r = conn.execute(text(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_type = 'BASE TABLE' ORDER BY table_name"
            ))
            tables = [row[0] for row in r]
        print("Connection: OK")
        print("Tables:", ", ".join(tables) if tables else "(none)")
        return True
    except Exception as e:
        print("Connection failed:", e)
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Initialize database: ensure .env, optionally create DB/user, run migrations, verify."
    )
    parser.add_argument(
        "--create-db",
        action="store_true",
        help="Create PostgreSQL user and database, then write DATABASE_URL to .env",
    )
    parser.add_argument(
        "--db-name",
        default="samgov_db",
        help="Database name (default: samgov_db)",
    )
    parser.add_argument(
        "--db-user",
        default="samgov_user",
        help="Database user (default: samgov_user)",
    )
    parser.add_argument(
        "--db-password",
        default="",
        help="Password for new user (default: auto-generated if --create-db)",
    )
    parser.add_argument(
        "--sync-password",
        action="store_true",
        help="Set PostgreSQL user password to match DATABASE_URL in .env",
    )
    parser.add_argument(
        "--skip-migrations",
        action="store_true",
        help="Do not run alembic upgrade head",
    )
    args = parser.parse_args()

    _ensure_project_root()
    _ensure_env()

    env_file = _env_path()
    try:
        from dotenv import load_dotenv
        load_dotenv(env_file)
    except ImportError:
        pass  # env may already be set

    if args.sync_password:
        url = _load_database_url()
        parsed = _parse_db_url(url)
        if not parsed:
            print("Could not parse DATABASE_URL for sync-password.")
            sys.exit(1)
        user, password, *_ = parsed
        if not _sync_password(user, password):
            sys.exit(1)
        print("Done.")
        return 0

    if args.create_db:
        import secrets
        password = args.db_password or secrets.token_urlsafe(16)
        if not _create_db_and_user(args.db_name, args.db_user, password):
            sys.exit(1)
        url = f"postgresql://{args.db_user}:{password}@localhost:5432/{args.db_name}"
        # Update .env DATABASE_URL
        with open(env_file, "r") as f:
            content = f.read()
        if "DATABASE_URL=" in content:
            content = re.sub(
                r"DATABASE_URL=.*",
                "DATABASE_URL=" + url,
                content,
                count=1,
            )
        else:
            content = content.rstrip() + "\nDATABASE_URL=" + url + "\n"
        with open(env_file, "w") as f:
            f.write(content)
        print("Updated .env with DATABASE_URL")
        # Reload so migrations use new URL
        from dotenv import load_dotenv
        load_dotenv(env_file, override=True)

    if not args.skip_migrations:
        if not _run_migrations():
            sys.exit(1)

    if not _verify_connection():
        sys.exit(1)

    print("")
    print("Database initialization complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
