"""add_base_item_contract_type_extended_price_to_clins

Revision ID: 1733af08c87f
Revises: cb8968c32e55
Create Date: 2026-01-19 04:51:42.774798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1733af08c87f'
down_revision = 'cb8968c32e55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clins', sa.Column('base_item_number', sa.String(length=50), nullable=True))
    op.add_column('clins', sa.Column('contract_type', sa.String(length=100), nullable=True))
    op.add_column('clins', sa.Column('extended_price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clins', 'extended_price')
    op.drop_column('clins', 'contract_type')
    op.drop_column('clins', 'base_item_number')
    # ### end Alembic commands ###
