"""add_notice_id_and_description_to_opportunities

Revision ID: 222c56f7ec35
Revises: 68db1451ef6c
Create Date: 2026-01-18 22:24:11.391797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222c56f7ec35'
down_revision = '68db1451ef6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('notice_id', sa.String(length=100), nullable=True))
    op.add_column('opportunities', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_opportunities_notice_id'), 'opportunities', ['notice_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunities_notice_id'), table_name='opportunities')
    op.drop_column('opportunities', 'description')
    op.drop_column('opportunities', 'notice_id')
    # ### end Alembic commands ###
