"""add_contact_info_to_opportunities

Revision ID: cb8968c32e55
Revises: 222c56f7ec35
Create Date: 2026-01-19 00:36:38.197057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8968c32e55'
down_revision = '222c56f7ec35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('primary_contact', sa.JSON(), nullable=True))
    op.add_column('opportunities', sa.Column('alternative_contact', sa.JSON(), nullable=True))
    op.add_column('opportunities', sa.Column('contracting_office_address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'contracting_office_address')
    op.drop_column('opportunities', 'alternative_contact')
    op.drop_column('opportunities', 'primary_contact')
    # ### end Alembic commands ###
